default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        name: Ruff check (with fix)
        args: [--fix]

      - id: ruff-format
        name: Ruff format
